<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />

    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="Moq.EntityFrameworkCore" Version="10.0.0.2" />

    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\server\App01\App01.Bootstrapper.Api\App01.Bootstrapper.Api.csproj" />
    <ProjectReference Include="..\..\..\..\src\server\App01\App01.Modules.Lotto\App01.Modules.Lotto.csproj" />
    <ProjectReference Include="..\..\..\..\src\server\App01\App01.Modules.Portal\App01.Modules.Portal.csproj" />    
    <ProjectReference Include="..\..\..\..\src\server\App01\App01.Shared.Infrastructure\App01.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
