// <auto-generated />
using System;
using App01.Shared.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App01.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007063845_CoursesInitial")]
    partial class CoursesInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App01.Shared.Application.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses", "Courses");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.Draw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DrawSystemId")
                        .HasColumnType("bigint");

                    b.Property<int>("DrawTypeId")
                        .HasColumnType("int");

                    b.Property<long>("NumbersHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("NumbersLow")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialsHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialsLow")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DrawDate")
                        .HasDatabaseName("IX_Draws_DrawDate");

                    b.HasIndex("DrawSystemId")
                        .HasDatabaseName("IX_Draws_DrawSystemId");

                    b.HasIndex("DrawTypeId", "DrawDate")
                        .HasDatabaseName("IX_Draws_DrawTypeId_DrawDate");

                    b.HasIndex("DrawTypeId", "DrawSystemId", "DrawDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Draws_DrawTypeId_DrawSystemId_DrawDate");

                    b.ToTable("Draws", "Lotto");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.DrawType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumbersCount")
                        .HasColumnType("int");

                    b.Property<int>("NumbersMaxValue")
                        .HasColumnType("int");

                    b.Property<int>("SpecialsCount")
                        .HasColumnType("int");

                    b.Property<int>("SpecialsMaxValue")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserNumbersCountMax")
                        .HasColumnType("int");

                    b.Property<int>("UserNumbersCountMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DrawTypes", "Lotto");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.DrawTypeWinTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrawTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NumbersMatchCount")
                        .HasColumnType("int");

                    b.Property<int>("NumbersMatchSelected")
                        .HasColumnType("int");

                    b.Property<decimal>("PotentialWinPrize")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("SpecialsMatchCount")
                        .HasColumnType("int");

                    b.Property<int>("SpecialsMatchSelected")
                        .HasColumnType("int");

                    b.Property<int>("WinTier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawTypeId");

                    b.ToTable("DrawTypeWinTiers", "Lotto");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawTypeId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("NumbersHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("NumbersLow")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialsHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecialsLow")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DrawTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets", "Lotto");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Portal.Mail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Mails", "Portal");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Portal.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "Portal");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.Draw", b =>
                {
                    b.HasOne("App01.Shared.Application.Entities.Lotto.DrawType", "DrawType")
                        .WithMany("Draws")
                        .HasForeignKey("DrawTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrawType");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.DrawTypeWinTier", b =>
                {
                    b.HasOne("App01.Shared.Application.Entities.Lotto.DrawType", "DrawType")
                        .WithMany("DrawTypeWinTiers")
                        .HasForeignKey("DrawTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrawType");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.Ticket", b =>
                {
                    b.HasOne("App01.Shared.Application.Entities.Lotto.DrawType", "DrawType")
                        .WithMany()
                        .HasForeignKey("DrawTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App01.Shared.Application.Entities.Portal.User", "User")
                        .WithMany("LottoTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrawType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Lotto.DrawType", b =>
                {
                    b.Navigation("DrawTypeWinTiers");

                    b.Navigation("Draws");
                });

            modelBuilder.Entity("App01.Shared.Application.Entities.Portal.User", b =>
                {
                    b.Navigation("LottoTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
