using App01.Shared.Application.Entities.Portal;
using App01.Shared.Application.Exceptions;
using App01.Shared.Application.Interfaces;
using App01.Shared.Infrastructure.Repositories;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace App01.Modules.Portal.Features.UsersRegister;


public class Handler : IRequestHandler<Contracts.Request, Contracts.Response>
{
    private const string PasswordPrefix = "Student";
    private const string PasswordSuffix = "!";

    private readonly ILogger<Handler> _logger;
    private readonly IValidator<Contracts.Request> _validator;
    private readonly AppDbContext _dbContext;
    private readonly IJwtService _jwtService;

    public Handler(
        ILogger<Handler> logger,
        IValidator<Contracts.Request> validator,
        AppDbContext dbContext,
        IJwtService jwtService)
    {
        _logger = logger;
        _validator = validator;
        _dbContext = dbContext;
        _jwtService = jwtService;
    }

    public async Task<Contracts.Response> Handle(Contracts.Request request, CancellationToken cancellationToken)
    {
        var validationResult = await _validator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
        {
            throw new ValidationException(validationResult.Errors);
        }

        var isCallerAdmin = await _jwtService.GetIsAdminFromJwt();
        if (!isCallerAdmin)
        {
            throw new ForbiddenException("Only administrators can register users in bulk");
        }

        var emails = request.Users
            .Select(u => u.Email.Trim())
            .ToList();

        var existingEmails = await _dbContext.Users
            .Where(u => emails.Contains(u.Email))
            .Select(u => u.Email)
            .ToListAsync(cancellationToken);

        if (existingEmails.Count > 0)
        {
            throw new ValidationException($"Users with these emails already exist: {string.Join(", ", existingEmails)}");
        }

        var createdAt = DateTime.Now;
        var users = emails
            .Select(email => new User
            {
                Email = email,
                PasswordHash = string.Empty,
                IsAdmin = false,
                CreatedAt = createdAt
            })
            .ToList();

        var transaction = _dbContext.Database.IsRelational()
            ? await _dbContext.Database.BeginTransactionAsync(cancellationToken)
            : null;

        await using (transaction)
        {
            // Id is generated by the database, so users are persisted first
            // and only then the password ("Student" + Id + "!") can be hashed.
            _dbContext.Users.AddRange(users);
            await _dbContext.SaveChangesAsync(cancellationToken);

            foreach (var user in users)
            {
                user.PasswordHash = BCrypt.Net.BCrypt.HashPassword($"{PasswordPrefix}{user.Id}{PasswordSuffix}");
            }

            await _dbContext.SaveChangesAsync(cancellationToken);

            if (transaction != null)
            {
                await transaction.CommitAsync(cancellationToken);
            }
        }

        _logger.LogDebug("Registered {Count} users: {UserIds}", users.Count, string.Join(", ", users.Select(u => u.Id)));

        return new Contracts.Response(
            users.Select(u => new Contracts.RegisteredUserDto(u.Id, u.Email)).ToList());
    }
}
